---
#title: "collected_original_DSA_text"
#author: "Andrea Tentner"
#date: "10/28/2021"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## NIDA Data Share

Data Use Agreement

Thank you for visiting the NIDA Datashare web site and reviewing our data sharing policy. Before entering the data site, you must first agree to the following terms and conditions:

The recipient of the data agrees:

1. Not to use the received data, either alone or in conjunction with any other information, in any effort whatsoever to establish identities of any of the subjects from whom the data were obtained.
2. To retain control over the received data, and not to transfer any portion of the received data, with or without charge, to any other entity or individual
3. To notify the Recipient's Institutional Review Board (IRB) operating under an Assurance approved by the Office of Human Research Protections (OHRP) as required by the Recipient's affiliated university, and in accordance with Department of Health and Human Services regulations at 45 CRF Part 46 of any new research projects based on the NIDA data. This requirement is university-specific and is not necessary for data uses such as teaching resources.
4. To acknowledge the NIDA database and the specific trials accessed in all oral and written presentations and publications resulting from analyses of the received data. NIDA data should be cited as follows: “The information reported here results from secondary analyses of data from clinical trials conducted by the National Institute on Drug Abuse (NIDA). Specifically, data from <actual protocol number and title> were included. NIDA databases and information are available at http://datashare.nida.nih.gov
5. To maintain security and privacy of the received data for as long as necessary per local and federal requirements.
6. To inform the NIDA Data Manager when research paper(s) that include the use of NIDA data, is (are) accepted for publication.
That NIDA or its affiliates may contact you concerning publications or other issues regarding use of the data.

